
const STRAPI_URL = 'http://localhost:1337';
const EMAIL = 'jdhanco1@gmail.com';
const PASSWORD = 'Admin12345!';

// We need to use node-fetch or native fetch.
// Assuming Node 18+, native fetch is available.

async function getToken() {
  console.log('Authenticating as Admin...');
  try {
    // 1. Login as Admin
    const loginResponse = await fetch(`${STRAPI_URL}/admin/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: EMAIL, password: PASSWORD }),
    });

    if (!loginResponse.ok) {
        console.error('Login failed:', loginResponse.status, loginResponse.statusText);
        const text = await loginResponse.text();
        console.error('Body:', text);
        return null;
    }

    const loginData = await loginResponse.json();
    const adminToken = loginData.data?.token;

    if (!adminToken) {
        console.error('No admin token received');
        return null;
    }

    console.log('Admin authenticated. Creating full-access API Token...');

    // 2. Create API Token
    // Endpoint for creating API tokens in Strapi v4/v5
    // Note: The payload structure might vary slightly, but this is standard for v4.
    const tokenName = `Seed-Token-${Date.now()}`;
    const tokenResponse = await fetch(`${STRAPI_URL}/admin/api-tokens`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${adminToken}`
        },
        body: JSON.stringify({
            name: tokenName,
            description: "Generated by seed script helper",
            type: "full-access", // "read-only", "full-access", "custom"
            lifespan: null
        })
    });

    if (!tokenResponse.ok) {
         console.error('Token creation failed:', tokenResponse.status, tokenResponse.statusText);
         const text = await tokenResponse.text();
         console.error('Body:', text);
         return null;
    }

    const tokenData = await tokenResponse.json();
    // The created token object should contain the accessKey
    // Response format: { data: { id, name, ..., accessKey: "..." } }
    if (tokenData.data && tokenData.data.accessKey) {
        return tokenData.data.accessKey;
    }
    
    console.error('Access key not found in token response:', tokenData);
    return null;

  } catch (error) {
    console.error('Error in token flow:', error);
    return null;
  }
}

async function run() {
  const token = await getToken();
  
  if (token) {
    console.log(`\n✅ Generated API Token: ${token.substring(0, 10)}...`);
    console.log('Running cms/seed.js with this token...\n');
    
    const { spawn } = require('child_process');
    
    // Run the seed script with the new token
    const child = spawn('node', ['cms/seed.js'], {
        env: { ...process.env, STRAPI_TOKEN: token, STRAPI_URL: STRAPI_URL },
        stdio: 'inherit' // Pipe output directly to console
    });
    
    child.on('close', (code) => {
        console.log(`\nSeed script finished with code ${code}`);
    });
  } else {
      console.log('Failed to get token. Script aborted.');
  }
}

run();
